/**
 * AgeZero UI Registry — a 21st.dev-style catalog of installable elements.
 *
 * Each entry describes a single element (component, block, or section)
 * that consumers can browse on `/registry` and install via the AgeZero UI
 * CLI (or by copy-pasting the snippet). The shape mirrors the
 * `shadcn registry` schema so the same CLI conventions apply.
 */

export type RegistryDependency = {
  /** npm package name, e.g. "@radix-ui/react-dialog". */
  name: string;
  /** Optional semver range. Defaults to "latest". */
  version?: string;
  /** Whether this is a dev-only dependency. */
  dev?: boolean;
};

export type RegistryEntry = {
  /** Unique slug used in URLs and the CLI. */
  name: string;
  /** Human-friendly title for the registry UI. */
  title: string;
  /** Short description shown in the card. */
  description: string;
  /** Top-level group for filtering. */
  category: "ui" | "ai" | "block" | "icon" | "section";
  /** The npm-style import path once installed. */
  importPath: string;
  /** A short, copy-pasteable install snippet. */
  install: string;
  /** npm packages the consumer must have installed. */
  dependencies: RegistryDependency[];
  /** Other registry items this entry depends on (slugs). */
  registryDependencies?: string[];
  /** Optional preview tags used in the gallery. */
  tags?: string[];
};

export const registry: RegistryEntry[] = [
  // ─── UI primitives ─────────────────────────────────────────────────
  {
    name: "button",
    title: "Button",
    description: "6 variants × 4 sizes, asChild via Radix Slot.",
    category: "ui",
    importPath: "@/components/ui/button",
    install: "pnpm dlx agezero-ui add button",
    dependencies: [
      { name: "@radix-ui/react-slot" },
      { name: "class-variance-authority" },
    ],
    tags: ["primitive", "form"],
  },
  {
    name: "card",
    title: "Card",
    description: "Header, title, description, content, footer, action.",
    category: "ui",
    importPath: "@/components/ui/card",
    install: "pnpm dlx agezero-ui add card",
    dependencies: [],
    tags: ["primitive", "layout"],
  },
  {
    name: "input",
    title: "Input",
    description: "forwardRef, focus ring, file: styling, aria-invalid.",
    category: "ui",
    importPath: "@/components/ui/input",
    install: "pnpm dlx agezero-ui add input",
    dependencies: [],
    tags: ["form", "primitive"],
  },
  {
    name: "label",
    title: "Label",
    description: "Radix Label wrapper for accessible form labels.",
    category: "ui",
    importPath: "@/components/ui/label",
    install: "pnpm dlx agezero-ui add label",
    dependencies: [{ name: "@radix-ui/react-label" }],
    tags: ["form", "a11y"],
  },
  {
    name: "badge",
    title: "Badge",
    description: "6 variants incl. success and warning.",
    category: "ui",
    importPath: "@/components/ui/badge",
    install: "pnpm dlx agezero-ui add badge",
    dependencies: [{ name: "class-variance-authority" }],
    tags: ["primitive"],
  },
  {
    name: "avatar",
    title: "Avatar",
    description: "Radix Avatar with image and fallback initials.",
    category: "ui",
    importPath: "@/components/ui/avatar",
    install: "pnpm dlx agezero-ui add avatar",
    dependencies: [{ name: "@radix-ui/react-avatar" }],
    tags: ["primitive"],
  },
  {
    name: "separator",
    title: "Separator",
    description: "Horizontal and vertical Radix separator.",
    category: "ui",
    importPath: "@/components/ui/separator",
    install: "pnpm dlx agezero-ui add separator",
    dependencies: [{ name: "@radix-ui/react-separator" }],
    tags: ["primitive", "layout"],
  },
  {
    name: "textarea",
    title: "Textarea",
    description: "forwardRef, matches Input styling.",
    category: "ui",
    importPath: "@/components/ui/textarea",
    install: "pnpm dlx agezero-ui add textarea",
    dependencies: [],
    tags: ["form"],
  },
  {
    name: "dialog",
    title: "Dialog",
    description: "Animated modal with header, content, footer.",
    category: "ui",
    importPath: "@/components/ui/dialog",
    install: "pnpm dlx agezero-ui add dialog",
    dependencies: [{ name: "@radix-ui/react-dialog" }],
    tags: ["overlay", "a11y"],
  },
  {
    name: "dropdown-menu",
    title: "Dropdown menu",
    description: "Sections, items, checkbox/radio, sub-menus.",
    category: "ui",
    importPath: "@/components/ui/dropdown-menu",
    install: "pnpm dlx agezero-ui add dropdown-menu",
    dependencies: [{ name: "@radix-ui/react-dropdown-menu" }],
    tags: ["overlay"],
  },
  {
    name: "tabs",
    title: "Tabs",
    description: "Radix tabs with built-in keyboard navigation.",
    category: "ui",
    importPath: "@/components/ui/tabs",
    install: "pnpm dlx agezero-ui add tabs",
    dependencies: [{ name: "@radix-ui/react-tabs" }],
    tags: ["navigation"],
  },
  {
    name: "tooltip",
    title: "Tooltip",
    description: "Hover tooltip with provider, content, arrow.",
    category: "ui",
    importPath: "@/components/ui/tooltip",
    install: "pnpm dlx agezero-ui add tooltip",
    dependencies: [{ name: "@radix-ui/react-tooltip" }],
    tags: ["overlay"],
  },
  {
    name: "select",
    title: "Select",
    description: "Full Radix Select with viewport and scroll buttons.",
    category: "ui",
    importPath: "@/components/ui/select",
    install: "pnpm dlx agezero-ui add select",
    dependencies: [{ name: "@radix-ui/react-select" }],
    tags: ["form", "overlay"],
  },
  {
    name: "switch",
    title: "Switch",
    description: "Toggle switch with smooth animation.",
    category: "ui",
    importPath: "@/components/ui/switch",
    install: "pnpm dlx agezero-ui add switch",
    dependencies: [{ name: "@radix-ui/react-switch" }],
    tags: ["form", "primitive"],
  },
  {
    name: "slider",
    title: "Slider",
    description: "Single-value slider with Radix internals.",
    category: "ui",
    importPath: "@/components/ui/slider",
    install: "pnpm dlx agezero-ui add slider",
    dependencies: [{ name: "@radix-ui/react-slider" }],
    tags: ["form", "primitive"],
  },
  {
    name: "popover",
    title: "Popover",
    description: "Positioned panel with anchor support.",
    category: "ui",
    importPath: "@/components/ui/popover",
    install: "pnpm dlx agezero-ui add popover",
    dependencies: [{ name: "@radix-ui/react-popover" }],
    tags: ["overlay"],
  },
  {
    name: "combobox",
    title: "Combobox",
    description: "Searchable select with keyboard nav and filtering.",
    category: "ui",
    importPath: "@/components/ui/combobox",
    install: "pnpm dlx agezero-ui add combobox",
    dependencies: [{ name: "@radix-ui/react-slot" }],
    tags: ["form", "select"],
  },
  {
    name: "date-picker",
    title: "Date Picker",
    description: "Input + popover calendar with clear button.",
    category: "ui",
    importPath: "@/components/ui/date-picker",
    install: "pnpm dlx agezero-ui add date-picker",
    dependencies: [],
    tags: ["form", "date"],
  },
  {
    name: "calendar",
    title: "Calendar",
    description: "Month-grid date picker with prev/next navigation.",
    category: "ui",
    importPath: "@/components/ui/calendar",
    install: "pnpm dlx agezero-ui add calendar",
    dependencies: [],
    tags: ["date"],
  },
  {
    name: "pagination",
    title: "Pagination",
    description: "Page numbers + prev/next with sibling window + ellipses.",
    category: "ui",
    importPath: "@/components/ui/pagination",
    install: "pnpm dlx agezero-ui add pagination",
    dependencies: [],
    tags: ["navigation"],
  },
  {
    name: "breadcrumb",
    title: "Breadcrumb",
    description: "Hierarchical path with chevron or slash separators.",
    category: "ui",
    importPath: "@/components/ui/breadcrumb",
    install: "pnpm dlx agezero-ui add breadcrumb",
    dependencies: [],
    tags: ["navigation"],
  },
  {
    name: "steps",
    title: "Steps",
    description: "Stepper / progress indicator (horizontal or vertical).",
    category: "ui",
    importPath: "@/components/ui/steps",
    install: "pnpm dlx agezero-ui add steps",
    dependencies: [],
    tags: ["wizard", "progress"],
  },
  {
    name: "avatar-group",
    title: "Avatar Group",
    description: "Stacked row of avatars with overflow counter.",
    category: "ui",
    importPath: "@/components/ui/avatar-group",
    install: "pnpm dlx agezero-ui add avatar-group",
    dependencies: [],
    tags: ["avatar", "list"],
  },
  {
    name: "kbd",
    title: "Kbd",
    description: "Keyboard shortcut chip.",
    category: "ui",
    importPath: "@/components/ui/kbd",
    install: "pnpm dlx agezero-ui add kbd",
    dependencies: [],
    tags: ["primitive"],
  },
  {
    name: "skeleton",
    title: "Skeleton",
    description: "Loading placeholder with pulse animation.",
    category: "ui",
    importPath: "@/components/ui/skeleton",
    install: "pnpm dlx agezero-ui add skeleton",
    dependencies: [],
    tags: ["loading"],
  },
  {
    name: "empty-state",
    title: "Empty State",
    description: "Centered placeholder for empty data / no results.",
    category: "ui",
    importPath: "@/components/ui/empty-state",
    install: "pnpm dlx agezero-ui add empty-state",
    dependencies: [],
    tags: ["placeholder"],
  },
  {
    name: "toast",
    title: "Toast",
    description: "Auto-dismissing notifications (success/error/info).",
    category: "ui",
    importPath: "@/components/ui/toast",
    install: "pnpm dlx agezero-ui add toast",
    dependencies: [],
    tags: ["feedback"],
  },
  {
    name: "resizable",
    title: "Resizable",
    description: "Two-pane split with mouse and keyboard resize.",
    category: "ui",
    importPath: "@/components/ui/resizable",
    install: "pnpm dlx agezero-ui add resizable",
    dependencies: [],
    tags: ["layout"],
  },
  {
    name: "collapsible",
    title: "Collapsible",
    description: "Show/hide panel using native details element.",
    category: "ui",
    importPath: "@/components/ui/collapsible",
    install: "pnpm dlx agezero-ui add collapsible",
    dependencies: [],
    tags: ["disclosure"],
  },
  {
    name: "hover-card",
    title: "Hover Card",
    description: "Hover-revealed popover with configurable delays.",
    category: "ui",
    importPath: "@/components/ui/hover-card",
    install: "pnpm dlx agezero-ui add hover-card",
    dependencies: [],
    tags: ["overlay"],
  },
  {
    name: "data-table",
    title: "Data Table",
    description: "Sortable table with custom cells and row keys.",
    category: "ui",
    importPath: "@/components/ui/data-table",
    install: "pnpm dlx agezero-ui add data-table",
    dependencies: [],
    tags: ["table", "data"],
  },
  {
    name: "tag-input",
    title: "Tag Input",
    description: "Chip-style multi-input with suggestions.",
    category: "ui",
    importPath: "@/components/ui/tag-input",
    install: "pnpm dlx agezero-ui add tag-input",
    dependencies: [],
    tags: ["form", "tags"],
  },

  // ─── AI components ─────────────────────────────────────────────────
  {
    name: "message",
    title: "Message",
    description: "Chat bubble with role + avatar + content + actions.",
    category: "ai",
    importPath: "@/components/ai/message",
    install: "pnpm dlx agezero-ui add message",
    dependencies: [],
    tags: ["chat", "agent"],
  },
  {
    name: "conversation",
    title: "Conversation",
    description: "Auto-scrolling chat thread with empty state.",
    category: "ai",
    importPath: "@/components/ai/conversation",
    install: "pnpm dlx agezero-ui add conversation",
    dependencies: [],
    tags: ["chat"],
  },
  {
    name: "prompt-input",
    title: "Prompt Input",
    description: "Auto-grow textarea with tool slots and submit.",
    category: "ai",
    importPath: "@/components/ai/prompt-input",
    install: "pnpm dlx agezero-ui add prompt-input",
    dependencies: [],
    tags: ["chat", "form"],
  },
  {
    name: "reasoning",
    title: "Reasoning",
    description: "Collapsible chain-of-thought trace.",
    category: "ai",
    importPath: "@/components/ai/reasoning",
    install: "pnpm dlx agezero-ui add reasoning",
    dependencies: [],
    tags: ["agent", "trace"],
  },
  {
    name: "tool",
    title: "Tool",
    description: "Tool-call display with collapsible output.",
    category: "ai",
    importPath: "@/components/ai/tool",
    install: "pnpm dlx agezero-ui add tool",
    dependencies: [],
    tags: ["agent"],
  },
  {
    name: "sources",
    title: "Sources",
    description: "Citation list with title, description, link.",
    category: "ai",
    importPath: "@/components/ai/sources",
    install: "pnpm dlx agezero-ui add sources",
    dependencies: [],
    tags: ["rag", "citation"],
  },
  {
    name: "agent-card",
    title: "Agent Card",
    description: "Status-coded agent tile (idle/running/done/error).",
    category: "ai",
    importPath: "@/components/ai/agent-card",
    install: "pnpm dlx agezero-ui add agent-card",
    dependencies: [],
    tags: ["agent", "card"],
  },
  {
    name: "code-block",
    title: "Code Block",
    description: "Lightweight TS/JS/Python syntax highlighting.",
    category: "ai",
    importPath: "@/components/ai/code-block",
    install: "pnpm dlx agezero-ui add code-block",
    dependencies: [],
    tags: ["code"],
  },
  {
    name: "artifact",
    title: "Artifact",
    description: "Preview panel with header and close button.",
    category: "ai",
    importPath: "@/components/ai/artifact",
    install: "pnpm dlx agezero-ui add artifact",
    dependencies: [],
    tags: ["preview"],
  },
  {
    name: "loader",
    title: "Loader",
    description: "Dots, spinner, and bars loaders.",
    category: "ai",
    importPath: "@/components/ai/loader",
    install: "pnpm dlx agezero-ui add loader",
    dependencies: [],
    tags: ["feedback"],
  },

  // ─── Marketing blocks (21st.dev-style) ─────────────────────────────
  {
    name: "hero",
    title: "Hero",
    description: "Big headline, tagline, two CTAs, badge row.",
    category: "block",
    importPath: "@/components/blocks/hero",
    install: "pnpm dlx agezero-ui add hero",
    dependencies: [],
    tags: ["marketing", "landing"],
  },
  {
    name: "feature-grid",
    title: "Feature Grid",
    description: "3×2 grid of icon + title + description tiles.",
    category: "block",
    importPath: "@/components/blocks/feature-grid",
    install: "pnpm dlx agezero-ui add feature-grid",
    dependencies: [],
    tags: ["marketing", "features"],
  },
  {
    name: "bento",
    title: "Bento Grid",
    description: "Mixed-size bento grid for showcasing features.",
    category: "block",
    importPath: "@/components/blocks/bento",
    install: "pnpm dlx agezero-ui add bento",
    dependencies: [],
    tags: ["marketing", "features"],
  },
  {
    name: "pricing",
    title: "Pricing",
    description: "3-tier pricing table with a highlighted middle tier.",
    category: "block",
    importPath: "@/components/blocks/pricing",
    install: "pnpm dlx agezero-ui add pricing",
    dependencies: [],
    tags: ["marketing", "pricing"],
  },
  {
    name: "stats",
    title: "Stats",
    description: "4-column animated stats strip.",
    category: "block",
    importPath: "@/components/blocks/stats",
    install: "pnpm dlx agezero-ui add stats",
    dependencies: [],
    tags: ["marketing", "social-proof"],
  },
  {
    name: "testimonials",
    title: "Testimonials",
    description: "3-column customer quote grid with avatar.",
    category: "block",
    importPath: "@/components/blocks/testimonials",
    install: "pnpm dlx agezero-ui add testimonials",
    dependencies: [],
    tags: ["marketing", "social-proof"],
  },
  {
    name: "logo-cloud",
    title: "Logo Cloud",
    description: "Strip of partner / customer logos.",
    category: "block",
    importPath: "@/components/blocks/logo-cloud",
    install: "pnpm dlx agezero-ui add logo-cloud",
    dependencies: [],
    tags: ["marketing", "social-proof"],
  },
  {
    name: "cta",
    title: "Call to action",
    description: "Bottom-of-page CTA section with two buttons.",
    category: "block",
    importPath: "@/components/blocks/cta",
    install: "pnpm dlx agezero-ui add cta",
    dependencies: [],
    tags: ["marketing", "conversion"],
  },

  // ─── Additional marketing blocks ────────────────────────────────────
  {
    name: "marquee",
    title: "Marquee",
    description: "Infinite horizontally scrolling strip with pause-on-hover.",
    category: "block",
    importPath: "@/components/blocks/marquee",
    install: "pnpm dlx agezero-ui add marquee",
    dependencies: [],
    tags: ["marketing", "animation"],
  },
  {
    name: "dock",
    title: "Dock",
    description: "macOS-style floating dock with magnify-on-hover.",
    category: "block",
    importPath: "@/components/blocks/dock",
    install: "pnpm dlx agezero-ui add dock",
    dependencies: [],
    tags: ["marketing", "navigation"],
  },
  {
    name: "timeline",
    title: "Timeline",
    description: "Vertical event list with connecting line and icons.",
    category: "block",
    importPath: "@/components/blocks/timeline",
    install: "pnpm dlx agezero-ui add timeline",
    dependencies: [],
    tags: ["marketing", "history"],
  },
  {
    name: "faq",
    title: "FAQ",
    description: "Accordion list using native <details> elements.",
    category: "block",
    importPath: "@/components/blocks/faq",
    install: "pnpm dlx agezero-ui add faq",
    dependencies: [],
    tags: ["marketing", "support"],
  },
  {
    name: "comparison",
    title: "Comparison table",
    description: "Feature-vs-product table with boolean or string cells.",
    category: "block",
    importPath: "@/components/blocks/comparison",
    install: "pnpm dlx agezero-ui add comparison",
    dependencies: [],
    tags: ["marketing", "pricing"],
  },
  {
    name: "animated-tabs",
    title: "Animated tabs",
    description: "Tab strip with sliding CSS indicator.",
    category: "block",
    importPath: "@/components/blocks/animated-tabs",
    install: "pnpm dlx agezero-ui add animated-tabs",
    dependencies: [],
    tags: ["navigation", "animation"],
  },
  {
    name: "spotlight",
    title: "Spotlight card",
    description: "Card that follows the cursor with a soft radial highlight.",
    category: "block",
    importPath: "@/components/blocks/spotlight",
    install: "pnpm dlx agezero-ui add spotlight",
    dependencies: [],
    tags: ["interactive", "marketing"],
  },
  {
    name: "gradient-text",
    title: "Gradient text",
    description: "Text with a gradient fill, optionally animated.",
    category: "block",
    importPath: "@/components/blocks/gradient-text",
    install: "pnpm dlx agezero-ui add gradient-text",
    dependencies: [],
    tags: ["text", "animation"],
  },

  // ─── Motion elements ────────────────────────────────────────────────
  {
    name: "fade-in",
    title: "FadeIn",
    description: "Fade + slide-in on mount with direction/delay/distance.",
    category: "block",
    importPath: "@/components/motion/fade-in",
    install: "pnpm dlx agezero-ui add fade-in",
    dependencies: [],
    tags: ["motion", "animation"],
  },
  {
    name: "scroll-reveal",
    title: "ScrollReveal",
    description: "Fade + slide-in when scrolled into view via IntersectionObserver.",
    category: "block",
    importPath: "@/components/motion/scroll-reveal",
    install: "pnpm dlx agezero-ui add scroll-reveal",
    dependencies: [],
    tags: ["motion", "scroll"],
  },
  {
    name: "count-up",
    title: "CountUp",
    description: "Animates a number from 0 to value with ease-out cubic.",
    category: "block",
    importPath: "@/components/motion/count-up",
    install: "pnpm dlx agezero-ui add count-up",
    dependencies: [],
    tags: ["motion", "stats"],
  },
  {
    name: "typewriter",
    title: "Typewriter",
    description: "Types out text character by character, optional phrase cycling.",
    category: "block",
    importPath: "@/components/motion/typewriter",
    install: "pnpm dlx agezero-ui add typewriter",
    dependencies: [],
    tags: ["motion", "text"],
  },
  {
    name: "shimmer",
    title: "Shimmer",
    description: "Loading skeleton with animated gradient sweep.",
    category: "block",
    importPath: "@/components/motion/shimmer",
    install: "pnpm dlx agezero-ui add shimmer",
    dependencies: [],
    tags: ["motion", "loading"],
  },
  {
    name: "pulse",
    title: "Pulse",
    description: "Glowing radial pulse behind its children. Good for CTAs.",
    category: "block",
    importPath: "@/components/motion/pulse",
    install: "pnpm dlx agezero-ui add pulse",
    dependencies: [],
    tags: ["motion", "highlight"],
  },
  {
    name: "glow-card",
    title: "GlowCard",
    description: "Card that follows the cursor with a soft radial glow.",
    category: "block",
    importPath: "@/components/motion/glow-card",
    install: "pnpm dlx agezero-ui add glow-card",
    dependencies: [],
    tags: ["motion", "interactive"],
  },
  {
    name: "tilt-3d",
    title: "Tilt3D",
    description: "3D tilt on hover following the cursor with perspective.",
    category: "block",
    importPath: "@/components/motion/tilt-3d",
    install: "pnpm dlx agezero-ui add tilt-3d",
    dependencies: [],
    tags: ["motion", "interactive"],
  },
  {
    name: "magnetic",
    title: "Magnetic",
    description: "Pulls content toward the cursor like a magnet.",
    category: "block",
    importPath: "@/components/motion/magnetic",
    install: "pnpm dlx agezero-ui add magnetic",
    dependencies: [],
    tags: ["motion", "cta"],
  },
  {
    name: "gradient-border",
    title: "GradientBorder",
    description: "Animated conic gradient ring around children.",
    category: "block",
    importPath: "@/components/motion/gradient-border",
    install: "pnpm dlx agezero-ui add gradient-border",
    dependencies: [],
    tags: ["motion", "decoration"],
  },
  {
    name: "mcp-server",
    title: "MCP server",
    description: "Model Context Protocol server for icon search in Claude/Cursor/Continue.",
    category: "section",
    importPath: "@agezero-ui/mcp",
    install: "pnpm add -g @agezero-ui/mcp",
    dependencies: [],
    tags: ["tooling", "ai"],
  },
  // ─── Hooks ───────────────────────────────────────────────────────────
  {
    name: "use-debounce",
    title: "useDebounce",
    description: "Debounce a fast-changing value to a stable one.",
    category: "section",
    importPath: "@/hooks/use-debounce",
    install: "pnpm dlx agezero-ui add use-debounce",
    dependencies: [],
    tags: ["hooks", "performance"],
  },
  {
    name: "use-local-storage",
    title: "useLocalStorage",
    description: "Persistent state in localStorage with SSR safety.",
    category: "section",
    importPath: "@/hooks/use-local-storage",
    install: "pnpm dlx agezero-ui add use-local-storage",
    dependencies: [],
    tags: ["hooks", "state"],
  },
  {
    name: "use-media-query",
    title: "useMediaQuery",
    description: "Reactive CSS media query match status.",
    category: "section",
    importPath: "@/hooks/use-media-query",
    install: "pnpm dlx agezero-ui add use-media-query",
    dependencies: [],
    tags: ["hooks", "responsive"],
  },
  {
    name: "use-click-outside",
    title: "useClickOutside",
    description: "Detect pointer events outside a ref (close popovers).",
    category: "section",
    importPath: "@/hooks/use-click-outside",
    install: "pnpm dlx agezero-ui add use-click-outside",
    dependencies: [],
    tags: ["hooks", "a11y"],
  },
  {
    name: "use-intersection",
    title: "useIntersection",
    description: "IntersectionObserver as a hook, with freeze-once-visible.",
    category: "section",
    importPath: "@/hooks/use-intersection",
    install: "pnpm dlx agezero-ui add use-intersection",
    dependencies: [],
    tags: ["hooks", "animation"],
  },
  {
    name: "use-copy-to-clipboard",
    title: "useCopyToClipboard",
    description: "navigator.clipboard wrapper with copied state and reset.",
    category: "section",
    importPath: "@/hooks/use-copy-to-clipboard",
    install: "pnpm dlx agezero-ui add use-copy-to-clipboard",
    dependencies: [],
    tags: ["hooks", "ux"],
  },
  {
    name: "use-is-client",
    title: "useIsClient",
    description: "Returns true after the component mounts (SSR guard).",
    category: "section",
    importPath: "@/hooks/use-is-client",
    install: "pnpm dlx agezero-ui add use-is-client",
    dependencies: [],
    tags: ["hooks", "ssr"],
  },
  // ─── AI (extra) ─────────────────────────────────────────────────────
  {
    name: "streaming-text",
    title: "StreamingText",
    description: "Incremental text rendering with a blinking cursor.",
    category: "ai",
    importPath: "@/components/ai/streaming-text",
    install: "pnpm dlx agezero-ui add streaming-text",
    dependencies: [],
    tags: ["ai", "stream"],
  },
  {
    name: "token-counter",
    title: "TokenCounter",
    description: "Live token usage display with a progress bar.",
    category: "ai",
    importPath: "@/components/ai/token-counter",
    install: "pnpm dlx agezero-ui add token-counter",
    dependencies: [],
    tags: ["ai", "meter"],
  },
  {
    name: "model-selector",
    title: "ModelSelector",
    description: "Grid of selectable model cards with vendor + cost tiers.",
    category: "ai",
    importPath: "@/components/ai/model-selector",
    install: "pnpm dlx agezero-ui add model-selector",
    dependencies: [],
    tags: ["ai", "selector"],
  },
  {
    name: "citation",
    title: "Citation",
    description: "Inline citation marker that expands on hover.",
    category: "ai",
    importPath: "@/components/ai/citation",
    install: "pnpm dlx agezero-ui add citation",
    dependencies: [],
    tags: ["ai", "annotation"],
  },
  // ─── Blocks (extra) ─────────────────────────────────────────────────
  {
    name: "confetti",
    title: "Confetti",
    description: "One-shot confetti burst, with reduced-motion opt-out.",
    category: "block",
    importPath: "@/components/blocks/confetti",
    install: "pnpm dlx agezero-ui add confetti",
    dependencies: [],
    tags: ["celebration", "motion"],
  },
  {
    name: "scroll-progress",
    title: "ScrollProgress",
    description: "Reading-progress bar that fills as the user scrolls.",
    category: "block",
    importPath: "@/components/blocks/scroll-progress",
    install: "pnpm dlx agezero-ui add scroll-progress",
    dependencies: [],
    tags: ["ux", "motion"],
  },
  {
    name: "parallax",
    title: "Parallax",
    description: "Subtle scroll-driven parallax transform.",
    category: "block",
    importPath: "@/components/blocks/parallax",
    install: "pnpm dlx agezero-ui add parallax",
    dependencies: [],
    tags: ["motion", "decoration"],
  },
  {
    name: "animated-number",
    title: "AnimatedNumber",
    description: "Counter that eases to its value on mount or on view.",
    category: "block",
    importPath: "@/components/blocks/animated-number",
    install: "pnpm dlx agezero-ui add animated-number",
    dependencies: [],
    tags: ["motion", "stat"],
  },
  // ─── Charts ─────────────────────────────────────────────────────────
  {
    name: "sparkline",
    title: "Sparkline",
    description: "Tiny line chart with optional fill — fits inside cards.",
    category: "block",
    importPath: "@/components/charts/sparkline",
    install: "pnpm dlx agezero-ui add sparkline",
    dependencies: [],
    tags: ["chart", "data"],
  },
  {
    name: "bar",
    title: "Bar",
    description: "Vertical bar chart with labels and values.",
    category: "block",
    importPath: "@/components/charts/bar",
    install: "pnpm dlx agezero-ui add bar",
    dependencies: [],
    tags: ["chart", "data"],
  },
  {
    name: "donut",
    title: "Donut",
    description: "Donut chart with a center label and legend.",
    category: "block",
    importPath: "@/components/charts/donut",
    install: "pnpm dlx agezero-ui add donut",
    dependencies: [],
    tags: ["chart", "data"],
  },
  // ─── Mobile ────────────────────────────────────────────────────────
  {
    name: "mobile-drawer",
    title: "MobileDrawer",
    description: "Slide-in side drawer for mobile nav (left/right/bottom).",
    category: "ui",
    importPath: "@/components/mobile/mobile-drawer",
    install: "pnpm dlx agezero-ui add mobile-drawer",
    dependencies: [],
    tags: ["mobile", "drawer"],
  },
  {
    name: "bottom-sheet",
    title: "BottomSheet",
    description: "Bottom-anchored sheet that drags to dismiss.",
    category: "ui",
    importPath: "@/components/mobile/bottom-sheet",
    install: "pnpm dlx agezero-ui add bottom-sheet",
    dependencies: [],
    tags: ["mobile", "sheet"],
  },
  {
    name: "swipeable",
    title: "Swipeable",
    description: "Swipe-to-dismiss / swipe-to-action list item.",
    category: "ui",
    importPath: "@/components/mobile/swipeable",
    install: "pnpm dlx agezero-ui add swipeable",
    dependencies: [],
    tags: ["mobile", "gesture"],
  },
  {
    name: "responsive-tabs",
    title: "ResponsiveTabs",
    description: "Tabs that become a select on small viewports.",
    category: "ui",
    importPath: "@/components/mobile/responsive-tabs",
    install: "pnpm dlx agezero-ui add responsive-tabs",
    dependencies: [],
    tags: ["mobile", "tabs"],
  },
  {
    name: "touch-target",
    title: "TouchTarget",
    description: "Wraps any element to ensure 44×44 px touch target.",
    category: "ui",
    importPath: "@/components/mobile/touch-target",
    install: "pnpm dlx agezero-ui add touch-target",
    dependencies: [],
    tags: ["mobile", "a11y"],
  },
  // ─── SEO / JSON-LD ────────────────────────────────────────────────
  {
    name: "json-ld",
    title: "JsonLd",
    description: "Drop-in Google Rich Results JSON-LD script tag.",
    category: "ui",
    importPath: "@/components/seo/json-ld",
    install: "pnpm dlx agezero-ui add json-ld",
    dependencies: [],
    tags: ["seo"],
  },
  // ─── Templates ─────────────────────────────────────────────────────
  {
    name: "docs-template",
    title: "Docs Template",
    description: "3-column docs page: nav, content, TOC.",
    category: "section",
    importPath: "@/components/templates/docs",
    install: "pnpm dlx agezero-ui add docs-template",
    dependencies: [],
    tags: ["template", "docs"],
  },
  {
    name: "auth-template",
    title: "Auth Template",
    description: "Sign-in / sign-up card with social buttons.",
    category: "section",
    importPath: "@/components/templates/auth",
    install: "pnpm dlx agezero-ui add auth-template",
    dependencies: [],
    tags: ["template", "auth"],
  },
  {
    name: "status-template",
    title: "Status Template",
    description: "Public status page: components + incident timeline.",
    category: "section",
    importPath: "@/components/templates/status",
    install: "pnpm dlx agezero-ui add status-template",
    dependencies: [],
    tags: ["template", "status"],
  },
  // ─── Motion (Wave 3 additions) ─────────────────────────────────────
  {
    name: "parallax-mouse",
    title: "ParallaxMouse",
    description: "Damped mouse-parallax wrapper.",
    category: "section",
    importPath: "@/components/motion/parallax-mouse",
    install: "pnpm dlx agezero-ui add parallax-mouse",
    dependencies: [],
    tags: ["motion", "parallax"],
  },
  {
    name: "mask-reveal",
    title: "MaskReveal",
    description: "Clip-path mask reveal on viewport enter.",
    category: "section",
    importPath: "@/components/motion/mask-reveal",
    install: "pnpm dlx agezero-ui add mask-reveal",
    dependencies: [],
    tags: ["motion", "reveal"],
  },
  {
    name: "stagger-children",
    title: "StaggerChildren",
    description: "Stagger entrance for a list of children.",
    category: "section",
    importPath: "@/components/motion/stagger-children",
    install: "pnpm dlx agezero-ui add stagger-children",
    dependencies: [],
    tags: ["motion", "list"],
  },
  {
    name: "number-flip",
    title: "NumberFlip",
    description: "Animated number counter for value changes.",
    category: "section",
    importPath: "@/components/motion/number-flip",
    install: "pnpm dlx agezero-ui add number-flip",
    dependencies: [],
    tags: ["motion", "counter"],
  },
  // ─── AI (Wave 3 additions) ─────────────────────────────────────────
  {
    name: "voice-input",
    title: "VoiceInput",
    description: "Web Speech API mic button with transcript callback.",
    category: "ai",
    importPath: "@/components/ai/voice-input",
    install: "pnpm dlx agezero-ui add voice-input",
    dependencies: [],
    tags: ["ai", "voice"],
  },
  {
    name: "multimodal-input",
    title: "MultimodalInput",
    description: "Chat input with image attachments and previews.",
    category: "ai",
    importPath: "@/components/ai/multimodal-input",
    install: "pnpm dlx agezero-ui add multimodal-input",
    dependencies: [],
    tags: ["ai", "input", "media"],
  },
  {
    name: "conversation-branch",
    title: "ConversationBranch",
    description: "Tree of conversation branches with switch and fork.",
    category: "ai",
    importPath: "@/components/ai/conversation-branch",
    install: "pnpm dlx agezero-ui add conversation-branch",
    dependencies: [],
    tags: ["ai", "tree"],
  },
  {
    name: "agent-trace",
    title: "AgentTrace",
    description: "Recursive tree of agent execution steps with timing.",
    category: "ai",
    importPath: "@/components/ai/agent-trace",
    install: "pnpm dlx agezero-ui add agent-trace",
    dependencies: [],
    tags: ["ai", "debug"],
  },
  {
    name: "webhook-card",
    title: "WebhookCard",
    description: "Display a webhook config, status, and recent payload.",
    category: "ai",
    importPath: "@/components/ai/webhook-card",
    install: "pnpm dlx agezero-ui add webhook-card",
    dependencies: [],
    tags: ["ai", "webhook"],
  },
  {
    name: "system-prompt",
    title: "SystemPrompt",
    description: "Tinted card to display the model's system prompt.",
    category: "ai",
    importPath: "@/components/ai/system-prompt",
    install: "pnpm dlx agezero-ui add system-prompt",
    dependencies: [],
    tags: ["ai", "prompt"],
  },
  {
    name: "memory-viewer",
    title: "MemoryViewer",
    description: "Long-term memory inspector for agents.",
    category: "ai",
    importPath: "@/components/ai/memory-viewer",
    install: "pnpm dlx agezero-ui add memory-viewer",
    dependencies: [],
    tags: ["ai", "memory"],
  },
  {
    name: "prompt-template",
    title: "PromptTemplate",
    description: "Searchable library of saved prompt templates with vars.",
    category: "ai",
    importPath: "@/components/ai/prompt-template",
    install: "pnpm dlx agezero-ui add prompt-template",
    dependencies: [],
    tags: ["ai", "prompts"],
  },

  // ─── Wave 4 — backgrounds & ambient motion ──────────────────────
  {
    name: "aurora",
    title: "Aurora",
    description: "Radial gradient mesh background that slowly drifts.",
    category: "section",
    importPath: "@/components/motion/aurora",
    install: "pnpm dlx agezero-ui add aurora",
    dependencies: [],
    tags: ["motion", "background"],
  },
  {
    name: "grid-pattern",
    title: "GridPattern",
    description: "Repeating SVG grid with edge-mask fade.",
    category: "section",
    importPath: "@/components/motion/grid-pattern",
    install: "pnpm dlx agezero-ui add grid-pattern",
    dependencies: [],
    tags: ["motion", "background"],
  },
  {
    name: "dot-pattern",
    title: "DotPattern",
    description: "Repeating dot field background.",
    category: "section",
    importPath: "@/components/motion/dot-pattern",
    install: "pnpm dlx agezero-ui add dot-pattern",
    dependencies: [],
    tags: ["motion", "background"],
  },
  {
    name: "noise",
    title: "Noise",
    description: "SVG turbulence film-grain overlay.",
    category: "section",
    importPath: "@/components/motion/noise",
    install: "pnpm dlx agezero-ui add noise",
    dependencies: [],
    tags: ["motion", "background"],
  },
  {
    name: "beam",
    title: "Beam",
    description: "Border beam that sweeps around the perimeter.",
    category: "section",
    importPath: "@/components/motion/beam",
    install: "pnpm dlx agezero-ui add beam",
    dependencies: [],
    tags: ["motion", "highlight"],
  },
  {
    name: "meteors",
    title: "Meteors",
    description: "N falling-meteors background.",
    category: "section",
    importPath: "@/components/motion/meteors",
    install: "pnpm dlx agezero-ui add meteors",
    dependencies: [],
    tags: ["motion", "background"],
  },
  {
    name: "ripple",
    title: "Ripple",
    description: "Click ripple wrapper for any element.",
    category: "section",
    importPath: "@/components/motion/ripple",
    install: "pnpm dlx agezero-ui add ripple",
    dependencies: [],
    tags: ["motion", "feedback"],
  },
  {
    name: "animated-gradient",
    title: "AnimatedGradient",
    description: "Continuously-panning gradient background.",
    category: "section",
    importPath: "@/components/motion/animated-gradient",
    install: "pnpm dlx agezero-ui add animated-gradient",
    dependencies: [],
    tags: ["motion", "background"],
  },
  // ─── Wave 4 — Pro blocks (Magic UI Pro-inspired) ──────────────
  {
    name: "pro-header",
    title: "Pro Header",
    description: "Marketing header with mega-menu + mobile drawer.",
    category: "block",
    importPath: "@/components/blocks/pro-header",
    install: "pnpm dlx agezero-ui add pro-header",
    dependencies: [],
    tags: ["marketing", "navigation"],
  },
  {
    name: "pro-hero",
    title: "Pro Hero",
    description: "Hero with aurora background + typewriter + mockup slot.",
    category: "block",
    importPath: "@/components/blocks/pro-hero",
    install: "pnpm dlx agezero-ui add pro-hero",
    dependencies: [],
    tags: ["marketing", "hero"],
  },
  {
    name: "pro-pricing",
    title: "Pro Pricing",
    description: "3-tier pricing with monthly/yearly toggle.",
    category: "block",
    importPath: "@/components/blocks/pro-pricing",
    install: "pnpm dlx agezero-ui add pro-pricing",
    dependencies: [],
    tags: ["marketing", "pricing"],
  },
  // ─── Wave 4 — 18 AI app templates ─────────────────────────────
  {
    name: "app-chat-pdf",
    title: "Chat with PDF",
    description: "Full app template: upload PDF + chat with it.",
    category: "section",
    importPath: "@/components/app-templates/chat-with-pdf",
    install: "pnpm dlx agezero-ui add app-chat-pdf",
    dependencies: [],
    tags: ["app", "ai", "chat"],
  },
  {
    name: "app-chat-youtube",
    title: "Chat with YouTube",
    description: "Paste a YouTube URL, chat about the video.",
    category: "section",
    importPath: "@/components/app-templates/chat-with-youtube",
    install: "pnpm dlx agezero-ui add app-chat-youtube",
    dependencies: [],
    tags: ["app", "ai", "chat"],
  },
  {
    name: "app-deepseek-chat",
    title: "DeepSeek Chat",
    description: "DeepSeek-style chat with model picker + history.",
    category: "section",
    importPath: "@/components/app-templates/deepseek-chat",
    install: "pnpm dlx agezero-ui add app-deepseek-chat",
    dependencies: [],
    tags: ["app", "ai", "chat"],
  },
  {
    name: "app-gemini-chat",
    title: "Gemini Chat",
    description: "Gemini-style branded chat.",
    category: "section",
    importPath: "@/components/app-templates/gemini-chat",
    install: "pnpm dlx agezero-ui add app-gemini-chat",
    dependencies: [],
    tags: ["app", "ai", "chat"],
  },
  {
    name: "app-image-generation",
    title: "AI Image Generation",
    description: "Text-to-image playground.",
    category: "section",
    importPath: "@/components/app-templates/image-generation",
    install: "pnpm dlx agezero-ui add app-image-generation",
    dependencies: [],
    tags: ["app", "ai", "image"],
  },
  {
    name: "app-image-enhancer",
    title: "Image Enhancer",
    description: "Upscale + denoise photos.",
    category: "section",
    importPath: "@/components/app-templates/image-enhancer",
    install: "pnpm dlx agezero-ui add app-image-enhancer",
    dependencies: [],
    tags: ["app", "ai", "image"],
  },
  {
    name: "app-ghibli-image",
    title: "Ghibli Image Generator",
    description: "Style-transfer playground.",
    category: "section",
    importPath: "@/components/app-templates/ghibli-image-generator",
    install: "pnpm dlx agezero-ui add app-ghibli-image",
    dependencies: [],
    tags: ["app", "ai", "image"],
  },
  {
    name: "app-headshot",
    title: "Headshot Generator",
    description: "Selfie → professional headshot.",
    category: "section",
    importPath: "@/components/app-templates/headshot-generator",
    install: "pnpm dlx agezero-ui add app-headshot",
    dependencies: [],
    tags: ["app", "ai", "image"],
  },
  {
    name: "app-interior-design",
    title: "Interior Design Generator",
    description: "Re-design your room in 4 styles.",
    category: "section",
    importPath: "@/components/app-templates/interior-design-generator",
    install: "pnpm dlx agezero-ui add app-interior-design",
    dependencies: [],
    tags: ["app", "ai", "image"],
  },
  {
    name: "app-content-writer",
    title: "Content Writer AI",
    description: "Generate blog posts, emails, tweets.",
    category: "section",
    importPath: "@/components/app-templates/content-writer",
    install: "pnpm dlx agezero-ui add app-content-writer",
    dependencies: [],
    tags: ["app", "ai", "productivity"],
  },
  {
    name: "app-codeforge",
    title: "Codeforge",
    description: "AI build pipeline from prompt to production.",
    category: "section",
    importPath: "@/components/app-templates/codeforge-app",
    install: "pnpm dlx agezero-ui add app-codeforge",
    dependencies: [],
    tags: ["app", "ai", "productivity"],
  },
  {
    name: "app-changelog",
    title: "Changelog",
    description: "Reverse-chronological release notes.",
    category: "section",
    importPath: "@/components/app-templates/changelog-app",
    install: "pnpm dlx agezero-ui add app-changelog",
    dependencies: [],
    tags: ["app", "marketing"],
  },
  {
    name: "app-saas-landing",
    title: "SaaS Landing",
    description: "Premium SaaS marketing page.",
    category: "section",
    importPath: "@/components/app-templates/saas-landing-app",
    install: "pnpm dlx agezero-ui add app-saas-landing",
    dependencies: [],
    tags: ["app", "marketing"],
  },
  {
    name: "app-agent-roster",
    title: "Agent Roster",
    description: "Multi-agent AI team showcase.",
    category: "section",
    importPath: "@/components/app-templates/agent-app",
    install: "pnpm dlx agezero-ui add app-agent-roster",
    dependencies: [],
    tags: ["app", "ai", "productivity"],
  },
  {
    name: "app-blog",
    title: "Blog",
    description: "Editorial blog with featured + grid.",
    category: "section",
    importPath: "@/components/app-templates/blog-app",
    install: "pnpm dlx agezero-ui add app-blog",
    dependencies: [],
    tags: ["app", "marketing"],
  },
  {
    name: "app-portfolio",
    title: "Portfolio",
    description: "Personal portfolio with project grid.",
    category: "section",
    importPath: "@/components/app-templates/portfolio-app",
    install: "pnpm dlx agezero-ui add app-portfolio",
    dependencies: [],
    tags: ["app", "marketing"],
  },
  {
    name: "app-mobile-marketing",
    title: "Mobile App Marketing",
    description: "Phone-mockup marketing page.",
    category: "section",
    importPath: "@/components/app-templates/mobile-app",
    install: "pnpm dlx agezero-ui add app-mobile-marketing",
    dependencies: [],
    tags: ["app", "marketing"],
  },
  {
    name: "app-startup",
    title: "Startup Landing",
    description: "Dillionverma-style startup landing.",
    category: "section",
    importPath: "@/components/app-templates/startup-app",
    install: "pnpm dlx agezero-ui add app-startup",
    dependencies: [],
    tags: ["app", "marketing"],
  },
  // ─── CLI ────────────────────────────────────────────────────────────
  {
    name: "agezero-ui-cli",
    title: "agezero-ui CLI",
    description: "init / add / list / info / mcp commands — zero runtime deps.",
    category: "section",
    importPath: "agezero-ui",
    install: "npx agezero-ui <command>",
    dependencies: [],
    tags: ["tooling", "cli"],
  },
];

export function findRegistryEntry(name: string): RegistryEntry | undefined {
  return registry.find((entry) => entry.name === name);
}
